apiVersion: v1
kind: ConfigMap
metadata:
  name: my-app-container-config
  namespace: namespace-workflow-1769946356751
  labels:
    app.kubernetes.io/name: my-app-container
    kubernetes.azure.com/generator: devhub
data: